[project]
name = "do-not-refuse"
version = "0.0.0"
requires-python = ">=3.14"
dependencies = [
    "huggingface-hub>=1.27.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[project.scripts]
do-not-refuse = "do_not_refuse:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
